
# This file was *autogenerated* from the file ATFHE.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_61 = Integer(61); _sage_const_2048 = Integer(2048); _sage_const_1024 = Integer(1024); _sage_const_500 = Integer(500); _sage_const_64 = Integer(64); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_29 = Integer(29); _sage_const_32 = Integer(32)
load("lwe-estimator/estimator.py")

n=_sage_const_500 ; p = _sage_const_2 **_sage_const_13 ; q = _sage_const_2 **_sage_const_32 ;
alpha=sqrt(((q/p)**_sage_const_2 -_sage_const_1 )/_sage_const_12 )/q;
print(alpha)
print("lvl0")
costs = estimate_lwe(n, sqrt(_sage_const_2 *pi)*alpha, q, secret_distribution=(_sage_const_0 ,_sage_const_1 ))
print("lvl0,quantum")
costs = estimate_lwe(n, sqrt(_sage_const_2 *pi)*alpha, q, secret_distribution=(_sage_const_0 ,_sage_const_1 ), reduction_cost_model=BKZ.qsieve)

n=_sage_const_1024 ; p = _sage_const_2 **_sage_const_29 ; q = _sage_const_2 **_sage_const_32 ;
alpha=sqrt(((q/p)**_sage_const_2 -_sage_const_1 )/_sage_const_12 )/q;
print("lvl1")
costs = estimate_lwe(n, sqrt(_sage_const_2 *pi)*alpha, q, secret_distribution=(_sage_const_0 ,_sage_const_1 ))
print("lvl1,quantum")
costs = estimate_lwe(n, sqrt(_sage_const_2 *pi)*alpha, q, secret_distribution=(_sage_const_0 ,_sage_const_1 ), reduction_cost_model=BKZ.qsieve)

n=_sage_const_2048 ; p = _sage_const_2 **_sage_const_61 ; q = _sage_const_2 **_sage_const_64 ;
alpha=sqrt(((q/p)**_sage_const_2 -_sage_const_1 )/_sage_const_12 )/q;
print("lvl2")
costs = estimate_lwe(n, sqrt(_sage_const_2 *pi)*alpha, q, secret_distribution=(_sage_const_0 ,_sage_const_1 ))
print("lvl2,quantum")
costs = estimate_lwe(n, sqrt(_sage_const_2 *pi)*alpha, q, secret_distribution=(_sage_const_0 ,_sage_const_1 ), reduction_cost_model=BKZ.qsieve)

