
# This file was *autogenerated* from the file TFHE.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2p44en5 = RealNumber('2.44e-5'); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_63 = Integer(63); _sage_const_2 = Integer(2); _sage_const_1024 = Integer(1024); _sage_const_500 = Integer(500); _sage_const_64 = Integer(64); _sage_const_2048 = Integer(2048); _sage_const_31 = Integer(31); _sage_const_3p73en9 = RealNumber('3.73e-9'); _sage_const_32 = Integer(32)
load("lwe-estimator/estimator.py")

n=_sage_const_500 ; alpha=_sage_const_2p44en5 ; q = _sage_const_2 **_sage_const_32 ;
print("lvl0")
costs = estimate_lwe(n, sqrt(_sage_const_2 *pi)*alpha, q, secret_distribution=(_sage_const_0 ,_sage_const_1 ))
print("lvl0,quantum")
costs = estimate_lwe(n, sqrt(_sage_const_2 *pi)*alpha, q, secret_distribution=(_sage_const_0 ,_sage_const_1 ), reduction_cost_model=BKZ.qsieve)

n=_sage_const_1024 ; alpha = _sage_const_3p73en9 ; q = _sage_const_2 **_sage_const_32 ;
print("lvl1")
costs = estimate_lwe(n, sqrt(_sage_const_2 *pi)*alpha, q, secret_distribution=(_sage_const_0 ,_sage_const_1 ))
print("lvl1,quantum")
costs = estimate_lwe(n, sqrt(_sage_const_2 *pi)*alpha, q, secret_distribution=(_sage_const_0 ,_sage_const_1 ), reduction_cost_model=BKZ.qsieve)

n=_sage_const_1024 ; alpha = _sage_const_2 **(-_sage_const_31 ); q = _sage_const_2 **_sage_const_32 ;
print("lvl21KSK")
costs = estimate_lwe(n, sqrt(_sage_const_2 *pi)*alpha, q, secret_distribution=(_sage_const_0 ,_sage_const_1 ))
print("lvl21KSK,quantum")
costs = estimate_lwe(n, sqrt(_sage_const_2 *pi)*alpha, q, secret_distribution=(_sage_const_0 ,_sage_const_1 ), reduction_cost_model=BKZ.qsieve)

n=_sage_const_2048 ; alpha = _sage_const_2 **(-_sage_const_63 ); q = _sage_const_2 **_sage_const_64 ;
print("lvl2")
costs = estimate_lwe(n, sqrt(_sage_const_2 *pi)*alpha, q, secret_distribution=(_sage_const_0 ,_sage_const_1 ))
print("lvl2,quantum")
costs = estimate_lwe(n, sqrt(_sage_const_2 *pi)*alpha, q, secret_distribution=(_sage_const_0 ,_sage_const_1 ), reduction_cost_model=BKZ.qsieve)

