#!/usr/bin/env python3
"""Evaluate the two-level Smith refinement for TFHEpp ``lvl5bootparam``.

This checker keeps two questions separate.

* In an actual TFHEpp RLWE row, the public mask is uniform.  For fixed
  distinct secrets ``s,t``, the complete quadratic displacement is

      (t-s) * (A + g * (t+s)).

  Translation preserves uniformity of ``A``, so this displacement is uniform
  on the principal image generated by ``t-s``.  The two-level Smith theorem
  gives the exact image bit count ``K*n - (e*n+v)``.

* In the proof-only lossy branch, the public coefficient is replaced by a
  descriptor-carrying DSPR/NTRU small ratio.  TFHEpp does not instantiate that
  descriptor sampler.  The checker therefore reports the total 2-adic order a
  concrete descriptor would have to reach, but does not invent its law.

The implemented modular Gaussian is materialized through a signed-int64 lift.
Two error coefficients therefore differ in one of fewer than ``2^65``
integer values.  Without any coefficient independence assumption, a complete
degree-``n`` error-difference support has fewer than ``2^(65*n)`` elements.
Combining this support count with the exact Smith image and a union bound tests
every candidate in a cloud at once.  It is substantially stronger than the
older one-coordinate radius-two screen.

The script also emits exact Hasse dual-code weight enumerators for small
depths.  These are the polynomials used by the exact IID formula; no numerical
IID mass is claimed because ``std::normal_distribution`` does not specify a
portable exact probability mass function.
"""

from __future__ import annotations

import argparse
from collections import Counter
from dataclasses import asdict
import json
import math
from pathlib import Path
from typing import Any

from lvl5boot_gaussian_cluster import (
    SourceBinding,
    SourceParameters,
    orbit_size,
    read_tfhepp_sources,
)


def signed_fixed_weight_support_size(degree: int, weight: int) -> int:
    """Return ``2^weight * choose(degree, weight)`` exactly."""

    return (1 << weight) * math.comb(degree, weight)


def two_smith_order(degree: int, exponent: int, depth: int) -> int:
    """Return the chain order ``exponent * degree + depth``."""

    if exponent < 0 or not 0 <= depth < degree:
        raise ValueError("expected exponent >= 0 and 0 <= depth < degree")
    return exponent * degree + depth


def two_smith_image_bits(
    modulus_bits: int, degree: int, exponent: int, depth: int
) -> int:
    """Exact ``log2`` cardinality of the principal image."""

    order = two_smith_order(degree, exponent, depth)
    if order >= modulus_bits * degree:
        return 0
    return modulus_bits * degree - order


def hasse_dual_weight_enumerator(degree: int, depth: int) -> dict[int, int]:
    """Exact weight enumerator of the first ``depth`` binary Hasse rows.

    Lucas' theorem gives ``binom(i,j) mod 2 = 1`` exactly when every set bit
    of ``j`` is also a set bit of ``i``.  Python integers make the complete
    length-32768 rows compact bitsets, and Gray-code traversal changes one
    message bit at a time.  This is intended for modest depths; the production
    report stops at 16.
    """

    if degree <= 0 or degree & (degree - 1):
        raise ValueError("degree must be a positive power of two")
    if not 0 <= depth <= min(degree, 20):
        raise ValueError("exact enumerator depth must lie in [0,min(n,20)]")

    rows: list[int] = []
    for derivative in range(depth):
        row = 0
        for coefficient in range(degree):
            if coefficient & derivative == derivative:
                row |= 1 << coefficient
        rows.append(row)

    histogram: Counter[int] = Counter()
    word = 0
    previous_gray = 0
    for message in range(1 << depth):
        gray = message ^ (message >> 1)
        if message:
            changed = (gray ^ previous_gray).bit_length() - 1
            word ^= rows[changed]
        histogram[word.bit_count()] += 1
        previous_gray = gray
    return dict(sorted(histogram.items()))


def _cloud_screen(
    *,
    name: str,
    candidate_card: int,
    candidate_bits: int,
    params: SourceParameters,
    maximum_secret_order: int,
) -> dict[str, Any]:
    """Apply the correlation-safe finite-support union calculation."""

    degree = params.degree
    ambient_bits = params.modulus_bits * degree
    image_bits = ambient_bits - maximum_secret_order
    difference_box_bits = (params.signed_noise_bits + 1) * degree
    certified_exponent = image_bits - candidate_bits - difference_box_bits
    exact_log2_upper = (
        math.log2(candidate_card)
        + degree * math.log2(float((1 << (params.signed_noise_bits + 1)) - 1))
        - image_bits
    )

    # If totalOrder <= this threshold, the same coarse powers-of-two proof
    # still puts the complete union below 2^-targetBits.  The next integer is
    # the first order not rejected by this particular support calculation.
    screened_total_order = (
        (params.modulus_bits - params.signed_noise_bits - 1) * degree
        - candidate_bits
        - params.target_bits
    )
    first_unscreened_total_order = screened_total_order + 1
    first_unscreened_exponent, first_unscreened_depth = divmod(
        first_unscreened_total_order, degree
    )
    descriptor_order_needed_from_worst_secret = max(
        0, first_unscreened_total_order - maximum_secret_order
    )
    descriptor_exponent, descriptor_depth = divmod(
        descriptor_order_needed_from_worst_secret, degree
    )

    return {
        "name": name,
        "candidate_card": str(candidate_card),
        "candidate_log2": math.log2(candidate_card),
        "candidate_power_of_two_strict_upper": f"2^{candidate_bits}",
        "maximum_secret_difference_order_used": maximum_secret_order,
        "minimum_principal_image_bits": image_bits,
        "error_difference_box_power_of_two_strict_upper": (
            f"2^{difference_box_bits}"
        ),
        "exact_log2_union_upper_reporting_value": exact_log2_upper,
        "coarse_power_certificate": f"union probability < 2^-{certified_exponent}",
        "below_target": certified_exponent >= params.target_bits,
        "largest_total_order_still_screened_at_target": screened_total_order,
        "first_total_order_not_screened_at_target": {
            "order": first_unscreened_total_order,
            "exponent": first_unscreened_exponent,
            "depth": first_unscreened_depth,
        },
        "descriptor_order_needed_beyond_worst_secret_difference": {
            "order": descriptor_order_needed_from_worst_secret,
            "exponent": descriptor_exponent,
            "depth": descriptor_depth,
        },
    }


def analyse(binding: SourceBinding, hasse_depths: tuple[int, ...]) -> dict[str, Any]:
    params = binding.parameters
    params.validate()
    degree = params.degree
    weight = params.secret_weight

    full_secret_card = signed_fixed_weight_support_size(degree, weight)
    radius_two_card = sum(orbit_size(degree, weight, k) for k in range(3))

    # A distinct fixed-weight ternary difference has exponent zero when the
    # supports differ and exponent one when they agree.  Its nonzero primitive
    # binary reduction has Hasse depth at most n-1.
    support_changing_max_order = two_smith_order(degree, 0, degree - 1)
    same_support_max_order = two_smith_order(degree, 1, degree - 1)
    all_pairs_max_order = same_support_max_order

    radius_screen = _cloud_screen(
        name="radius_two",
        candidate_card=radius_two_card,
        candidate_bits=138,
        params=params,
        maximum_secret_order=all_pairs_max_order,
    )
    full_screen = _cloud_screen(
        name="complete_fixed_weight_codebook",
        candidate_card=full_secret_card,
        candidate_bits=1038,
        params=params,
        maximum_secret_order=all_pairs_max_order,
    )

    enumerators: dict[str, Any] = {}
    for depth in hasse_depths:
        histogram = hasse_dual_weight_enumerator(degree, depth)
        nonzero_weights = [value for value in histogram if value != 0]
        enumerators[str(depth)] = {
            "dimension": depth,
            "length": degree,
            "coefficient_sum": sum(histogram.values()),
            "minimum_nonzero_weight": min(nonzero_weights, default=0),
            "weight_coefficients": {
                str(codeword_weight): str(multiplicity)
                for codeword_weight, multiplicity in histogram.items()
            },
            "iid_formula": (
                "p_e^n * 2^-v * sum_w A_w * beta_e^w"
            ),
        }

    return {
        "source_binding": {
            **asdict(binding),
            "parameters": asdict(params),
        },
        "secret_space": {
            "law": "uniform fixed-weight signed ternary",
            "cardinality": str(full_secret_card),
            "log2_cardinality": math.log2(full_secret_card),
            "lean_checked_strict_upper": "2^1038",
            "radius_two_cardinality": str(radius_two_card),
            "radius_two_log2": math.log2(radius_two_card),
            "radius_two_lean_checked_strict_upper": "2^138",
        },
        "two_level_smith": {
            "ambient_bits": params.modulus_bits * degree,
            "image_formula": "K*n - (e*n+v)",
            "support_changing_branch": {
                "exponent": 0,
                "maximum_depth": degree - 1,
                "maximum_order": support_changing_max_order,
                "minimum_image_bits": (
                    params.modulus_bits * degree - support_changing_max_order
                ),
            },
            "same_support_branch": {
                "exponent": 1,
                "maximum_depth": degree - 1,
                "maximum_order": same_support_max_order,
                "minimum_image_bits": (
                    params.modulus_bits * degree - same_support_max_order
                ),
            },
            "exact_hasse_weight_enumerators": enumerators,
        },
        "implemented_finite_channel": {
            "coefficient_error_support": "[-2^63,2^63-1]",
            "coefficient_error_support_cardinality": "2^64",
            "coefficient_difference_cardinality": "2^65-1",
            "whole_ring_difference_support_strict_upper": (
                f"2^{(params.signed_noise_bits + 1) * degree}"
            ),
            "uses_coefficient_independence": False,
            "survives_fixed_descriptor_multiplication": True,
        },
        "uniform_public_mask_screens": {
            "radius_two": radius_screen,
            "complete_codebook": full_screen,
            "interpretation": (
                "For the actual uniform RLWE mask, translation by the quadratic "
                "term leaves the second factor uniform.  With probability at "
                "least one minus the reported union bound, every tested shifted "
                "finite-noise support is disjoint from the centre in this row."
            ),
        },
        "remaining_descriptor_boundary": {
            "concrete_tfhepp_small_ratio_descriptor_sampler": False,
            "reason": (
                "The DSPR/NTRU denominator, numerators, and Hermite masks are "
                "proof-family data, not TFHEpp key-generation parameters."
            ),
            "what_a_future_sampler_must_emit": (
                "A descriptor/leakage-weighted histogram of the total orders "
                "ord_pi((t-s)*(z_j+f*g_j*(t+s))) for every retained row."
            ),
            "full_codebook_first_unscreened_total_order": (
                full_screen["first_total_order_not_screened_at_target"]
            ),
        },
        "refinement_verdicts": {
            "exact_two_level_evaluator": (
                "DECISIVE_FAILURE_FOR_DIRECT_STATISTICAL_CLUSTER_WITH_UNIFORM_MASK"
            ),
            "complete_descriptor_multiplier": (
                "UNRESOLVED_WITHOUT_A_CONCRETE_LOSSY_DESCRIPTOR_SAMPLER"
            ),
            "correlated_fourier_theta": (
                "CANNOT_REPAIR_LITERAL_FINITE_SUPPORT_DISJOINTNESS_IN_SCREENED_STRATA"
            ),
            "anisotropic_information_set": (
                "NO_SOURCE_LEVEL_GAIN_FOR_IID_COEFFICIENT_ERRORS"
            ),
            "geometry_adapted_nonlocal_cluster": (
                "COMPLETE_CODEBOOK_ALREADY_SCREENED_FOR_THE_UNIFORM_MASK_LOW_ORDER_CASE"
            ),
            "overall": "COMPUTATIONAL_OR_CONCRETE_LOSSY_DESCRIPTOR_ROUTE_STILL_REQUIRED",
        },
        "scope": (
            "This is a proof-method obstruction, not an attack and not evidence "
            "that TFHEpp parameters are computationally insecure."
        ),
    }


def self_test(binding: SourceBinding) -> None:
    expected = SourceParameters(
        degree=1 << 15,
        secret_weight=96,
        modulus_bits=640,
        error_std_log2=33,
        gadget_base_bits=18,
        gadget_levels=35,
        auxiliary_base_bits=16,
        auxiliary_levels=40,
    )
    if binding.parameters != expected:
        raise AssertionError("parsed lvl5bootparam no longer matches the certificate")

    if two_smith_image_bits(8, 4, 1, 3) != 25:
        raise AssertionError("two-level image arithmetic changed")

    # Compare Lucas bit tests with direct binomial parity in a toy ring.
    toy = hasse_dual_weight_enumerator(8, 4)
    brute: Counter[int] = Counter()
    for message in range(1 << 4):
        word = []
        for coefficient in range(8):
            bit = 0
            for derivative in range(4):
                if message >> derivative & 1:
                    bit ^= math.comb(coefficient, derivative) & 1
            word.append(bit)
        brute[sum(word)] += 1
    if toy != dict(sorted(brute.items())):
        raise AssertionError("Hasse weight enumerator disagrees with direct parity")

    result = analyse(binding, (1, 2, 4, 8, 16))
    screens = result["uniform_public_mask_screens"]
    if not screens["radius_two"]["below_target"]:
        raise AssertionError("radius-two Smith screen lost its 128-bit margin")
    if not screens["complete_codebook"]["below_target"]:
        raise AssertionError("complete-codebook Smith screen lost its 128-bit margin")
    if (
        screens["complete_codebook"]["first_total_order_not_screened_at_target"]
        != {"order": 18840435, "exponent": 574, "depth": 31603}
    ):
        raise AssertionError("descriptor threshold changed")


def print_report(result: dict[str, Any]) -> None:
    params = result["source_binding"]["parameters"]
    smith = result["two_level_smith"]
    screens = result["uniform_public_mask_screens"]
    descriptor = result["remaining_descriptor_boundary"]

    print("TFHEpp lvl5boot two-level Smith screen")
    print(
        "  source-bound n={degree} q=2^{modulus_bits} w={secret_weight} "
        "signed-noise={signed_noise_bits} bits".format(**params)
    )
    print("exact two-level image")
    print(f"  ambient bits: {smith['ambient_bits']}")
    print(
        "  different support: order <= "
        f"{smith['support_changing_branch']['maximum_order']}, image bits >= "
        f"{smith['support_changing_branch']['minimum_image_bits']}"
    )
    print(
        "  same support: order <= "
        f"{smith['same_support_branch']['maximum_order']}, image bits >= "
        f"{smith['same_support_branch']['minimum_image_bits']}"
    )
    print("actual finite-support mask screens")
    for key in ("radius_two", "complete_codebook"):
        screen = screens[key]
        print(
            f"  {screen['name']}: {screen['coarse_power_certificate']}; "
            f"128-bit target={screen['below_target']}"
        )
    threshold = descriptor["full_codebook_first_unscreened_total_order"]
    print("lossy-descriptor boundary")
    print(
        "  first total order not rejected by the coarse 128-bit full-codebook "
        f"screen: {threshold['order']} = {threshold['exponent']}*n + "
        f"{threshold['depth']}"
    )
    print("  TFHEpp supplies no concrete DSPR/NTRU descriptor sampler")
    print("RESULT: " + result["refinement_verdicts"]["overall"])
    print(result["scope"])


def _parse_hasse_depths(value: str) -> tuple[int, ...]:
    depths = tuple(int(item) for item in value.split(",") if item)
    if not depths:
        raise argparse.ArgumentTypeError("at least one Hasse depth is required")
    if any(depth < 0 or depth > 20 for depth in depths):
        raise argparse.ArgumentTypeError("Hasse depths must lie in [0,20]")
    return depths


def parse_args() -> argparse.Namespace:
    workspace = Path(__file__).resolve().parents[3]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--tfhepp-root",
        type=Path,
        default=workspace / "TFHEpp",
        help="path to the TFHEpp checkout (default: sibling checkout)",
    )
    parser.add_argument(
        "--hasse-depths",
        type=_parse_hasse_depths,
        default=(1, 2, 4, 8, 16),
        help="comma-separated exact Hasse enumerator depths (default: 1,2,4,8,16)",
    )
    parser.add_argument("--json", action="store_true", help="emit JSON")
    parser.add_argument(
        "--self-test",
        action="store_true",
        help="validate source parsing and exact toy/enumerator arithmetic",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    binding = read_tfhepp_sources(args.tfhepp_root)
    if args.self_test:
        self_test(binding)
    result = analyse(binding, args.hasse_depths)
    if args.json:
        print(json.dumps(result, indent=2, sort_keys=True))
    else:
        print_report(result)


if __name__ == "__main__":
    main()
