

# This file was *autogenerated* from the file leakylwr.sage
from sage.all_cmdline import *   # import sage library

_sage_const_511 = Integer(511); _sage_const_512 = Integer(512); _sage_const_2 = Integer(2); _sage_const_8 = Integer(8); _sage_const_4 = Integer(4); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
load("./Geometric-LWE-Estimator/framework/LWR.sage")

n = _sage_const_511 
m = _sage_const_512 
q = _sage_const_2 **_sage_const_8 
p = _sage_const_2 **_sage_const_4 
D_s = {_sage_const_0 :_sage_const_1 /_sage_const_2 ,_sage_const_1 :_sage_const_1 /_sage_const_2 }
lwr_instance = LWR(n,p,q,m,D_s)
ebdd = lwe_instance.embed_into_EBDD()
beta, delta = ebdd.estimate_attack()

